# Generated by Django 2.2.5 on 2020-01-21 14:37

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_title', models.CharField(help_text='The title of the post', max_length=300)),
                ('post_text', models.CharField(help_text='The contents of the post', max_length=8000)),
                ('content_creator', models.CharField(help_text='The identity of the post creator', max_length=100)),
                ('date_published', models.DateTimeField(auto_now_add=True)),
                ('last_edit', models.DateTimeField(auto_now=True)),
                ('comments', django.contrib.postgres.fields.jsonb.JSONField()),
                ('post_image', models.BinaryField()),
            ],
        ),
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category_name', models.CharField(help_text='The category name', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ContentCreator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator_first_name', models.CharField(help_text='The person first name', max_length=30)),
                ('creator_middle_name', models.CharField(help_text='The person middle name', max_length=30)),
                ('creator_last_name', models.CharField(help_text='The person last name', max_length=30)),
                ('creator_email', models.EmailField(max_length=254)),
                ('creator_profile_pic', models.BinaryField()),
            ],
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(help_text='The tag text', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PostTagAssociation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.BlogPost')),
                ('tag_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Tags')),
            ],
        ),
        migrations.CreateModel(
            name='PostCategoriesAssociation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Categories')),
                ('post_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.BlogPost')),
            ],
        ),
    ]
