# Generated by Django 2.2.5 on 2020-02-14 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='content_creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.ContentCreator'),
        ),
    ]
