# Generated by Django 2.2.5 on 2020-02-14 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_statictext'),
    ]

    operations = [
        migrations.RunSQL(
            "INSERT INTO website_statictext (services_general) VALUES ('A unique text to verify that this is indeed changed and comming from the database')"
        ),
    ]
